[build]
# Define Nix packages to install (for Chrome and ChromeDriver)
packages = [
  "google-chrome",   # Google Chrome
  "chromedriver"     # ChromeDriver
]

# You can also use a custom build command if needed (but default Nixpacks should suffice)
# buildCommand = "pip install -r requirements.txt"

# Start command for your Python application
[deploy]
startCommand = "python app.py"

# Healthcheck path (you can adjust this based on your app’s endpoints)
healthcheckPath = "/"
