[build]
# Define Nix packages to install
packages = [
  "google-chrome",    # Google Chrome
  "chromedriver",     # ChromeDriver
  "glibc"             # GLIBC (may be required for compatibility)
]

[deploy]
startCommand = "python app.py"
