[build]
builder = "NIXPACKS"

# Include Python, Google Chrome, ChromeDriver, and other necessary packages
[build.nixpacksPlan.phases.setup]
nixPkgs = ["python311", "gcc", "unzip", "xvfb", "libxi6", "libgconf-2-4", "default-jdk"]

[build.nixpacksPlan.phases.install]
cmds = [
  "sudo apt-get update",
  "sudo apt-get install -y wget gnupg",
  "wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -",
  "sudo sh -c 'echo \"deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main\" > /etc/apt/sources.list.d/google-chrome.list'",
  "sudo apt-get update",
  "sudo apt-get install -y google-chrome-stable",
  "wget -N https://chromedriver.storage.googleapis.com/$(google-chrome --version | grep -oP '\\d+\\.\\d+\\.\\d+')/chromedriver_linux64.zip",
  "unzip chromedriver_linux64.zip",
  "sudo mv chromedriver /usr/bin/chromedriver",
  "sudo chmod +x /usr/bin/chromedriver",
  "python -m venv --copies /opt/venv",
  ". /opt/venv/bin/activate",
  "pip install -r requirements.txt"
]

[deploy]
startCommand = "python app.py"
healthcheckPath = "/"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
