[build]
builder = "nixpacks"
buildCommand = "echo building!"

# Specify Nix packages to ensure Chrome and ChromeDriver are installed
packages = [
  "google-chrome",    # Google Chrome
  "chromedriver"      # ChromeDriver
]

[deploy]
startCommand = "python app.py"  # Ensure the correct start command for your app
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "never"
