[build]
builder = "NIXPACKS"

# Include Python, Google Chrome, and ChromeDriver in the Nix environment
[build.nixpacksPlan.phases.setup]
nixPkgs = ["python311", "google-chrome-stable", "chromedriver"]

[build.nixpacksPlan.phases.install]
cmds = [
  "python -m venv --copies /opt/venv",
  ". /opt/venv/bin/activate",
  "pip install -r requirements.txt"
]

[deploy]
startCommand = "python app.py"
healthcheckPath = "/"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
