[build]
builder = "NIXPACKS"

# Use Nix to install Google Chrome and ChromeDriver
[build.nixpacksPlan.phases.setup]
nixPkgs = ["google-chrome", "chromedriver"]

[deploy]
startCommand = "python app.py"
healthcheckPath = "/"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
