[build]
builder = "NIXPACKS"

# Setup phase: install Python, Google Chrome, ChromeDriver, and additional dependencies using Nix
[build.nixpacksPlan.phases.setup]
nixPkgs = [
  "python311",
  "google-chrome",
  "chromedriver",
  "unzip",
  "xvfb",
  "libxi",
  "gconf",
  "jdk",
  "gcc"  # Include gcc for compiling if needed
]

# Install phase: create a virtual environment, activate it, and install Python dependencies
[build.nixpacksPlan.phases.install]
cmds = [
  "python -m venv --copies /opt/venv",
  ". /opt/venv/bin/activate",
  "pip install -r requirements.txt"
]

# Additional commands to be run after dependencies are installed
[build.nixpacksPlan.phases.install.after]
cmds = [
  # Download and set up the ChromeDriver
  "wget https://chromedriver.storage.googleapis.com/2.41/chromedriver_linux64.zip",
  "unzip chromedriver_linux64.zip",
  "sudo mv chromedriver /usr/bin/chromedriver",
  "sudo chown root:root /usr/bin/chromedriver",
  "sudo chmod +x /usr/bin/chromedriver"
]

[deploy]
startCommand = "python app.py"
healthcheckPath = "/"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
