[build]
# Use a custom build command to install Chrome and ChromeDriver using Nix
buildCommand = '''
nix-shell -p google-chrome chromedriver --run "pip install -r requirements.txt"
'''

[deploy]
# Start your Flask app
startCommand = "python app.py"

# Healthcheck endpoint
healthcheckPath = "/"
